import operator
from typing import Annotated, TypedDict, Optional, List, Dict, Any
from langchain_core.messages import AnyMessage
from langgraph.graph.message import add_messages

class SupervisorState(TypedDict):
    messages: Annotated[list[AnyMessage], add_messages]
    next: str  # Routing tag: "rag_agent", "booking_node", "query_node", "deep_memory_node", "web_search_fanout", "supervisor_sales_agent"
    user_id: str
    action_type: Optional[str]  # "RAG_SEARCH", "BOOKING_NODE", "QUERY_NODE", "DEEP_MEMORY", "WEB_SEARCH", "NONE"
    internal_facts: Annotated[List[Dict[str, Any]], operator.add]  # Aggregated facts returned by parallel sub-agents
    web_search_raw_results: Annotated[List[Dict[str, Any]], operator.add]  # Aggregated parallel Tavily search results
    web_search_queries: Optional[List[str]]  # Search queries generated by fanout node for worker execution
    pending_action_details: Optional[dict]  # HITL approval details for bookings/queries
    user_profile: Optional[dict]  # Slim core memory context (recent facts + latest summary)
    suggested_actions: Optional[List[str]]  # Max 3 follow-up actions generated by sales agent

